### ISSUE TITLE
Peer-peer review

### ISSUE THREAD

**Issue by Hector096** [KDlamini/awesome-books-javascript#4]
You did extremely great on this project! 👏 👏
There are however a few issues that you still need to work on to go to the next project but you are almost there! 🚦 🚦

-- Remove function is not working properly with the same author name.

**Comment by see-why** [comment]
Thanks a lot for spotting the bug

You can view the fix [in this pull request](https://github.com/KDlamini/awesome-books-javascript/pull/5).

Best Regards.
